#include "eeprom_map.h"


const unsigned short ADR_EE_BAT_ZAR_CNT[2]={EE_BAT1_ZAR_CNT,EE_BAT2_ZAR_CNT};
const unsigned short ADR_EE_BAT_ZAR_CNT_KE[2]={EE_BAT1_ZAR_CNT_KE,EE_BAT2_ZAR_CNT_KE};
const unsigned short ADR_EE_BAT_C_NOM[2]={EE_BAT1_C_NOM,EE_BAT2_C_NOM};
const unsigned short ADR_EE_BAT_YEAR_OF_ON[2]={EE_BAT1_YEAR_OF_ON,EE_BAT2_YEAR_OF_ON};
const unsigned short ADR_EE_BAT_IS_ON[2]={EE_BAT1_IS_ON,EE_BAT2_IS_ON};
const unsigned short ADR_EE_BAT_DAY_OF_ON[2]={EE_BAT1_DAY_OF_ON,EE_BAT2_DAY_OF_ON};
const unsigned short ADR_EE_BAT_MONTH_OF_ON[2]={EE_BAT1_MONTH_OF_ON,EE_BAT2_MONTH_OF_ON};
const unsigned short ADR_EE_BAT_RESURS[2]={EE_BAT1_RESURS,EE_BAT2_RESURS};
const unsigned short ADR_EE_BAT_C_REAL[2]={EE_BAT1_C_REAL,EE_BAT2_C_REAL};
//const unsigned short ADR_EE_BAT_TYPE[2]={EE_BAT1_TYPE,EE_BAT2_TYPE};
const unsigned short ADR_KUBAT[2]={EE_KUBAT1,EE_KUBAT2};
const unsigned short ADR_KUBATM[2]={EE_KUBATM1,EE_KUBATM2};
const unsigned short ADR_KI0BAT[2]={EE_KI0BAT1,EE_KI0BAT2};
const unsigned short ADR_KI1BAT[2]={EE_KI1BAT1,EE_KI1BAT2};
const unsigned short ADR_KTBAT[2]={EE_KTBAT1,EE_KTBAT2};


const unsigned short ADR_TMAX_EXT_EN[3]={EE_TMAX_EXT_EN0,EE_TMAX_EXT_EN1,EE_TMAX_EXT_EN2};
const unsigned short ADR_TMAX_EXT[3]={EE_TMAX_EXT0,EE_TMAX_EXT1,EE_TMAX_EXT2};
const unsigned short ADR_TMIN_EXT_EN[3]={EE_TMIN_EXT_EN0,EE_TMIN_EXT_EN1,EE_TMIN_EXT_EN2};
const unsigned short ADR_TMIN_EXT[3]={EE_TMIN_EXT0,EE_TMIN_EXT1,EE_TMIN_EXT2};
const unsigned short ADR_T_EXT_REL_EN[3]={EE_T_EXT_REL_EN0,EE_T_EXT_REL_EN1,EE_T_EXT_REL_EN2};
const unsigned short ADR_T_EXT_ZVUK_EN[3]={EE_T_EXT_ZVUK_EN0,EE_T_EXT_ZVUK_EN1,EE_T_EXT_ZVUK_EN2};
const unsigned short ADR_T_EXT_LCD_EN[3]={EE_T_EXT_LCD_EN0,EE_T_EXT_LCD_EN1,EE_T_EXT_LCD_EN2};
const unsigned short ADR_T_EXT_RS_EN[3]={EE_T_EXT_RS_EN0,EE_T_EXT_RS_EN1,EE_T_EXT_RS_EN2};

const unsigned short ADR_SK_SIGN[4]={EE_SK_SIGN0,EE_SK_SIGN1,EE_SK_SIGN2,EE_SK_SIGN3};
const unsigned short ADR_SK_REL_EN[4]={EE_SK_REL_EN0,EE_SK_REL_EN1,EE_SK_REL_EN2,EE_SK_REL_EN3};
const unsigned short ADR_SK_ZVUK_EN[4]={EE_SK_ZVUK_EN0,EE_SK_ZVUK_EN1,EE_SK_ZVUK_EN2,EE_SK_ZVUK_EN3};
const unsigned short ADR_SK_LCD_EN[4]={EE_SK_LCD_EN0,EE_SK_LCD_EN1,EE_SK_LCD_EN2,EE_SK_LCD_EN3};
const unsigned short ADR_SK_RS_EN[4]={EE_SK_RS_EN0,EE_SK_RS_EN1,EE_SK_RS_EN2,EE_SK_RS_EN3};

const unsigned short ADR_EE_RELE_SET_MASK[4]={EE_RELE_SET_MASK0,EE_RELE_SET_MASK1,EE_RELE_SET_MASK2,EE_RELE_SET_MASK3};

